### ISSUE TITLE
Create template for project task tracking

### ISSUE THREAD

**Issue by ryjones-dev** [webdevliteral/FishCardGame#1]
Learn how to use GitHub issues and projects to create tasks and sprint boards. Utilize automation to make task management easier.

### Tasks
- [x] Create issue to demonstrate project management functionality
- [x] Create a GitHub project to host tasks
- [x] Set up Planning and Kanban board to track task status
- [x] Create automation to automatically import labeled issues from this repository to the project
- [x] Create automation to close the corresponding issue in this repository when the task status is set to Done in the project
- [ ] Create follow up issues to capture any more needed project management tasks

**Comment by ryjones-dev** [comment]
The basics have been set up. I don't have any immediate follow up tickets, but if we find a need I will continue to edit project workflows as necessary.
